local PolePosition = {
    -- spawn = { x = 12671, y = 6413, z = 1, },
    doorKeys = {
        name = "Pole Position Key",
        doors = {
            { x = 12672, y = 6422, z = 0, },
        },
    },
    allowStories = "DWAP_PolePosition.KeepZombies",
    map = { name = "DWAP_PPStashMap1", },
    generators = {
        {
            controls = { sprite = "industry_02_67", x = 12658, y = 6400, z = 2, },
            fakeGenerators = {
                { x = 12662, y = 6406, z = -1, },
                { x = 12683, y = 6406, z = -1, },
            },
            solar = {
                powerbank = { sprite = "dwap_tiles_01_0", x = 12659, y = 6400, z = 2 },
                panels = {
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 5577,
                        y = 9374,
                        z = 1,
                        pb = 1,
                        spawn = false,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 5577,
                        y = 9373,
                        z = 1,
                        pb = 1,
                        spawn = false,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 5577,
                        y = 9372,
                        z = 1,
                        pb = 1,
                        spawn = false,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 5577,
                        y = 9371,
                        z = 1,
                        pb = 1,
                        spawn = false,
                    },
                }
            },
        },
    },
    waterTanks = {
        { sprite = "dwap_tiles_01_9", x = 12662, y = 6400, z = 2, },
    },
    waterFixtures = {
        { sprite = "fixtures_sinks_01_21", x = 12653, y = 6408, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_sinks_01_21", x = 12653, y = 6409, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_sinks_01_21", x = 12653, y = 6410, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_10", x = 12653, y = 6412, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_sinks_01_22", x = 12653, y = 6417, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_1", x = 12653, y = 6420, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_1", x = 12653, y = 6421, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_1", x = 12653, y = 6422, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_1", x = 12653, y = 6423, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_sinks_01_12", x = 12654, y = 6397, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_10", x = 12654, y = 6412, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_sinks_01_22", x = 12654, y = 6417, z = 0, sourceType="tank", source = 1, },
        { sprite = "appliances_laundry_01_0", x = 12655, y = 6397, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_10", x = 12655, y = 6412, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_sinks_01_22", x = 12655, y = 6417, z = 0, sourceType="tank", source = 1, },
        { sprite = "appliances_laundry_01_4", x = 12656, y = 6397, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_2", x = 12657, y = 6408, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_2", x = 12657, y = 6409, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_2", x = 12657, y = 6410, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_2", x = 12657, y = 6411, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_2", x = 12657, y = 6420, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_2", x = 12657, y = 6421, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_2", x = 12657, y = 6422, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_2", x = 12657, y = 6423, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_1", x = 12691, y = 6398, z = 0, sourceType="tank", source = 1, },
        { sprite = "appliances_laundry_01_1", x = 12691, y = 6400, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_sinks_01_16", x = 12691, y = 6413, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_sinks_01_17", x = 12692, y = 6405, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_sinks_01_12", x = 12693, y = 6397, z = 0, sourceType="tank", source = 1, },
    },
    loot = {
        {
            type = 'container',
            coords = {x=12673,y=6410,z=1},
            special = "essentials",
        },
        {
            type = 'container',
            coords = {x=12658,y=6420,z=1},
            special = 'skillmags',
            sandboxEnable = 'Loot_EnableBooks',
        },
        {
            type = 'container',
            coords = {x=12658,y=6421,z=1},
            sandboxEnable = 'SeedLibrary',
            special = 'SeedLibrary',
        },
        {
            type = 'container',
            coords = {x=12658,y=6422,z=1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        {
            type = 'container',
            coords = {x=12658,y=6423,z=1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        {
            type = 'container',
            coords = {x=12660,y=6418,z=1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=12670,y=6419,z=1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=12661,y=6418,z=1},
            dist = {"MedicalCabinet","ArmyStorageMedical", "ArmyBunkerMedical"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },


        {
            type = 'container',
            coords = {x=12658,y=6422,z=0},
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },

        {
            type = 'container',
            coords = {x=12691,y=6408,z=0},
            special = "kitchentools",
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12692,y=6414,z=0},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12693,y=6401,z=0},
            dist = { "FreezerRich", },
            distIncludeJunk = true,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12692,y=6397,z=0.5},
            dist = {"BathroomCounter","CrateToiletPaper", "GasStoreToiletries", "CrateLinens", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=12695,y=6395,z=0},
            dist = {"CrateLiquor", "DishCabinetVIPLounge", "BookstoreBiography", "BookstoreBusiness", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=12670,y=6400,z=0},
            dist = { "CrateLumber", "CrateSheetMetal", "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal", "ToolFactoryIngots" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=12670,y=6401,z=0},
            items = {
                { name = 'Base.NailsBox', },
                { name = 'Base.Sheet', },
                { name = 'Base.WoodAxe', },
                { name = 'Base.Machete', },
                { name = 'Base.Plank', },
                { name = 'Base.SteelBar', },
                { name = 'Base.PropaneTank', },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },

        {
            type = 'container',
            coords = {x=12670,y=6395,z=0},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=12670,y=6396,z=0},
            dist = {"CrateFishing", "FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        {
            type = 'container',
            coords = {x=12653,y=6409,z=1},
            dist = {"SewingStoreTools"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        {
            type = 'container',
            coords = {x=12653,y=6403,z=0},
            dist = { "LoggingFactoryTools", "CrateTools", "GarageTools", "BurglarTools", "CarpenterTools", "BarnTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
    },
}

return PolePosition
