local PolePosition = require "DWAP_PolePosition/configs/DWAP_PolePosition"
print("DWAP PolePosition extraLoot.lua loaded")
local extraLoot = {
    {
        type = 'container',
        coords = { x = 12661, y = 6399, z = 0 },
        dist = { "DrugShackDrugs" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_MedLevel",
    },
    {
        type = 'container',
        coords = { x = 12669, y = 6422, z = 0 },
        special = "gunlocker",
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = { x = 12653, y = 6404, z = 0 },
        dist = { "GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FarmLevel",
    },
    {
        type = 'container',
        coords = { x = 12653, y = 6405, z = 0 },
        items = {
            { name = 'Base.Fertilizer', chance = 1, count = { 8, 10 } },
        },
        randUntilFull = true,
        level = "Loot_FarmLevel",
    },
    {
        type = 'container',
        coords = { x = 12653, y = 6406, z = 0 },
        items = {
            { name = 'Base.AnimalFeedBag', chance = 1, count = { 9, 12 } },
        },
        randUntilFull = true,
        level = "Loot_FarmLevel",
    },
    {
        type = 'container',
        coords = { x = 12656, y = 6406, z = 0 },
        dist = { "CrateFishing", "FishermanTools" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FishLevel",
    },
    {
        type = 'container',
        coords = { x = 12657, y = 6406, z = 0 },
        dist = { "GunStoreKnives", "PawnShopKnives", },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = { x = 12683, y = 6397, z = 0 },
        dist = { "SafehouseTraps", },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = { x = 12683, y = 6398, z = 0 },
        dist = { "CarSupplyTools", "GasStorageMechanics", },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_ToolsLevel",
    },
    {
        type = 'container',
        coords = { x = 12683, y = 6399, z = 0 },
        dist = { "CampingStoreTools", "ArmyHangarTools", },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_ToolsLevel",
    },
    {
        type = 'container',
        coords = { x = 12683, y = 6400, z = 0 },
        dist = { "BurglarTools", "CarpenterTools", "BarnTools" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_ToolsLevel",
    },
    {
        type = 'container',
        coords = { x = 12683, y = 6407, z = 0 },
        dist = { "CrateLiquor" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12683, y = 6408, z = 0 },
        dist = { "CrateLiquor", "DishCabinetVIPLounge" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12682, y = 6409, z = 0 },
        dist = { "CrateLiquor", "DishCabinetVIPLounge" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12653, y = 6409, z = 0 },
        dist = { "BathroomCounter", "GasStoreToiletries", },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_LockersLevel",
    },
    {
        type = 'container',
        coords = { x = 12654, y = 6417, z = 0 },
        dist = { "BathroomCounter", "GasStoreToiletries", },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_LockersLevel",
    },
    {
        type = 'container',
        coords = { x = 12658, y = 6418, z = 0 },
        dist = { "CrateLumber", "CrateSheetMetal", "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal", "ToolFactoryIngots" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    {
        type = 'container',
        coords = { x = 12658, y = 6419, z = 0 },
        dist = { "CrateLumber", "CrateSheetMetal", "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal", "ToolFactoryIngots" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    {
        type = 'container',
        coords = { x = 12658, y = 6420, z = 0 },
        dist = { "CrateLumber", "CrateSheetMetal", "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal", "ToolFactoryIngots" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    {
        type = 'container',
        coords = { x = 12658, y = 6421, z = 0 },
        dist = { "CrateLumber", "CrateSheetMetal", "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal", "ToolFactoryIngots" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    {
        type = 'container',
        coords = { x = 12658, y = 6422, z = 0 },
        dist = { "ArmyStorageOutfit", "CampingStoreBackpacks", "ArmySurplusOutfit", "ToolStoreOutfit" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_LockersLevel",
    },
    {
        type = 'container',
        coords = { x = 12658, y = 6423, z = 0 },
        dist = { "ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateLinens" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_LockersLevel",
    },
    {
        type = 'container',
        coords = { x = 12691, y = 6405, z = 0 },
        dist = { "GigamartDryGoods", "CrateCannedFood", "KitchenCannedFood" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12692, y = 6405, z = 0 },
        dist = { "CrateFlour", "CrateOilVegetable" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12691, y = 6406, z = 0 },
        dist = { "ButcherSpices", "GigamartSpices", "GroceryBagGourmet", },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12691, y = 6408, z = 0 },
        dist = { "CrateFlour", "CrateOilVegetable", "CafeKitchenSupplies", "CafeKitchenTea", "CrateSodaBottles" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12691, y = 6411, z = 0 },
        dist = { "CrateButter" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
        frozen = true,
    },
    {
        type = 'container',
        coords = { x = 12691, y = 6412, z = 0 },
        dist = { "CafeteriaKitchenFreezer", },
        distIncludeJunk = false,
        randUntilFull = true,
        frozen = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12691, y = 6413, z = 0 },
        dist = { "CrateTortillaChips", "KitchenDryFood" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12691, y = 6414, z = 0 },
        dist = { "CafeKitchenSupplies", "CafeKitchenTea", "CrateSodaBottles" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12691, y = 6401, z = 0 },
        dist = { "FreezerRich", },
        distIncludeJunk = true,
        randUntilFull = true,
        frozen = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12692, y = 6401, z = 0 },
        dist = { "FreezerIceCream", },
        distIncludeJunk = false,
        randUntilFull = true,
        frozen = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12691, y = 6403, z = 0 },
        dist = { "WesternKitchenFreezer", "FreezerIceCream", },
        distIncludeJunk = false,
        randUntilFull = true,
        frozen = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12691, y = 6404, z = 0 },
        dist = { "FreezerRich", },
        distIncludeJunk = true,
        randUntilFull = true,
        frozen = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12693, y = 6404, z = 0 },
        dist = { "WesternKitchenFreezer", "FreezerIceCream", },
        distIncludeJunk = false,
        randUntilFull = true,
        frozen = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12693, y = 6400, z = 0 },
        dist = { "CrateToiletPaper" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 12670, y = 6420, z = 1 },
        special = "gunlocker",
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = { x = 12658, y = 6420, z = 1 },
        items = {
            { name = 'Base.Bag_ProtectiveCaseBulkyHazard', },
            { name = 'Base.Hat_NBCmask', },
            { name = 'Base.Glasses_SafetyGoggles', },
            { name = 'Base.Hat_BuildersRespirator', },
            { name = 'Base.HazmatSuit', },
            { name = 'Base.RespiratorFilters', },
            { name = 'Base.Hat_GasMask', },
            { name = 'Base.GasmaskFilter', },
        },
        randUntilFull = true,
        level = "Loot_LockersLevel",
    },
    {
        type = 'container',
        coords = { x = 12658, y = 6421, z = 1 },
        items = {
            { name = 'Base.Oxygen_Tank', },
        },
        randUntilFull = true,
        level = "Loot_LockersLevel",
    },
    {
        type = 'container',
        coords = { x = 12658, y = 6422, z = 1 },
        dist = { "ArmyStorageMedical", "ArmyBunkerMedical" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_MedLevel",
    },
    {
        type = 'container',
        coords = { x = 12658, y = 6423, z = 1 },
        dist = { "CrateRandomJunk", "LivingRoomShelfClassy", "StripClubDressers" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_LockersLevel",
    },
    {
        type = 'container',
        coords = { x = 12653, y = 6415, z = 1 },
        dist = { "CrateVHSTapes", "MovieRentalShelves" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_MediaLevel",
    },
    {
        type = 'container',
        coords = { x = 12653, y = 6416, z = 1 },
        dist = { "ClothingStorageWinter", "StripClubDressers" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_LockersLevel",
    },
    {
        type = 'container',
        coords = { x = 12653, y = 6417, z = 1 },
        dist = { "LaundryLoad1", "ArmySurplusOutfit", "StripClubDressers" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_LockersLevel",
    },
    {
        type = 'container',
        coords = { x = 12653, y = 6419, z = 1 },
        dist = { "CrateBootsArmy", "GunStoreKnives", "LivingRoomShelfRedneck", "StripClubDressers", },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_LockersLevel",
    },
    {
        type = 'container',
        coords = { x = 12653, y = 6420, z = 1 },
        dist = { "DrugLabOutfit", "StripClubDressers" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_LockersLevel",
    },
    {
        type = 'container',
        coords = { x = 12653, y = 6421, z = 1 },
        dist = { "ArmyStorageOutfit", "StripClubDressers" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_LockersLevel",
    },
}

if PolePosition and PolePosition.loot then
    for i = 1, #extraLoot do
        table.insert(PolePosition.loot, extraLoot[i])
    end
end

return PolePosition
